=== iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/UD5/A3/ficheros/ejr5_xsd.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:complexType name="tipoDatos">
    <xs:sequence>
      <xs:element name="nombre" type="xs:string"/>
      <xs:element name="apellidos" type="xs:string"/>
      <xs:element name="dni" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="formaPagoTarjeta">
    <xs:sequence>
      <xs:element name="numeroTarjeta" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="formaPagoTransferencia">
    <xs:sequence>
      <xs:element name="numeroCuenta" type="xs:string"/>
    </xs:sequence>
  </xs:complexType>
  <xs:complexType name="tipoPersona">
    <xs:sequence>
      <xs:element name="datos" type="tipoDatos"/>
      <xs:element name="comentario" type="xs:string"/>
      <xs:choice>
        <xs:element name="tarjeta" type="formaPagoTarjeta"/>
        <xs:element name="transferencia" type="formaPagoTransferencia"/>
      </xs:choice>
    </xs:sequence>
    <xs:attribute name="fechaNacimiento" type="xs:date" use="optional"/>
  </xs:complexType>
  <xs:element name="personas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="persona" type="tipoPersona" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== iesgrancapitan-llmm/mi-primera-pagina-web-luisperezcantarero/UD5/A3/ficheros/Documento5.xml
<?xml version="1.0" encoding="UTF-8"?>
<personas xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ejr5_xsd.xsd">
  <persona fechaNacimiento="1985-04-12">
    <datos>
      <nombre>Juan</nombre>
      <apellidos>Pérez García</apellidos>
      <dni>12345678A</dni>
    </datos>
    <comentario>Una persona muy activa y entusiasta del deporte.</comentario>
    <tarjeta>
      <numeroTarjeta>1234567890123456</numeroTarjeta>
    </tarjeta>
  </persona>
  <persona>
    <datos>
      <nombre>Laura</nombre>
      <apellidos>Martínez Solís</apellidos>
      <dni>87654321B</dni>
    </datos>
    <comentario>Apasionada por la lectura y la escritura creativa.</comentario>
    <transferencia>
      <numeroCuenta>ES9820385778983000760236</numeroCuenta>
    </transferencia>
  </persona>
</personas>
