<?xml version="1.0" encoding="UTF-8"?>

<!DOCTYPE coches [
<!ELEMENT coches (coche+)>
<!ELEMENT coche (marca, modelo, puertas, color, precio)>
<!ATTLIST coche matricula CDATA #REQUIRED>
<!ELEMENT marca (#PCDATA)>
<!ELEMENT modelo (#PCDATA)>
<!ELEMENT puertas (#PCDATA)>
<!ELEMENT color (#PCDATA)>
<!ELEMENT precio (#PCDATA)>
<!ATTLIST precio venta CDATA #REQUIRED>
]>
<coches>
  <coche matricula="5078FXH">
    <marca>Seat</marca>
    <modelo>Ibiza</modelo>
    <puertas>5</puertas>
    <color>Verde</color>
    <precio venta="nuevo">18700</precio>
  </coche>
  <coche matricula="83055JKM">
    <marca>Renault</marca>
    <modelo>Clio</modelo>
    <puertas>5</puertas>
    <color>Naranja</color>
    <precio venta="ocasion">16200</precio>
  </coche>
</coches>