<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE colegio [
<!ELEMENT colegio (alumnos, profes)>
<!ELEMENT alumnos (alumno+)>
<!ELEMENT alumno (nombre, apellido, matricula, (activo | noactivo))>
<!ATTLIST alumno expediente CDATA #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT apellido (#PCDATA)>
<!ELEMENT matricula (#PCDATA)>
<!ELEMENT activo EMPTY>
<!ELEMENT noactivo EMPTY>
<!ELEMENT profes (profe)>
<!ELEMENT profe (nombre, curso, foto)>
<!ELEMENT curso (#PCDATA)>
<!ELEMENT foto (#PCDATA)>
]>
<colegio>
  <alumnos>
    <alumno expediente="AA01">
      <nombre>Luis</nombre>
      <apellido>Pérez</apellido>
      <matricula>DAW</matricula>
      <activo />
    </alumno>
    <alumno expediente="AA02">
      <nombre>José María</nombre>
      <apellido>Mayén</apellido>
      <matricula>DAW</matricula>
      <noactivo />
    </alumno>
  </alumnos>
  <profes>
    <profe>
      <nombre>Lourdes</nombre>
      <curso>DAW</curso>
      <foto>Lourdes.jpg</foto>
    </profe>
  </profes>
</colegio>
