<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE deportistas [
<!ELEMENT deportistas (deportista+)>
<!ELEMENT deportista (deporte, nombre)>
<!ELEMENT deporte (#PCDATA)>
<!ATTLIST deporte tipo ID #REQUIRED>
<!ELEMENT nombre (#PCDATA)>
]>
<deportistas>
  <deportista>
    <deporte tipo="Atletismo"/>
    <nombre>Jesse Owens</nombre>
  </deportista>
  <deportista>
    <deporte tipo="Natación"/>
    <nombre>Mark Spitz</nombre>
  </deportista>
</deportistas>
