<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE equipos [
<!ELEMENT equipos (equipo+)>
<!ELEMENT equipo ((local | visitante))>
<!ELEMENT local (nombre, goles)>
<!ELEMENT visitante (nombre, goles)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT goles (#PCDATA)>
]>
<equipos>
    <equipo>
        <local>
            <nombre>Nottingham Presa</nombre>
            <goles>0</goles>
        </local>
    </equipo>
    <equipo>
        <visitante>
            <nombre>Inter de Mitente</nombre>
            <goles>1</goles>
        </visitante>
    </equipo>
</equipos>