<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE peliculas [
<!ELEMENT peliculas (pelicula+)>
<!ELEMENT pelicula (titulo, director)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
]>
<peliculas>
  <pelicula>
    <titulo>Con faldas a lo loco</titulo>
    <director>Billy Wilder</director>
  </pelicula>
  <pelicula>
    <titulo>Sopa de ganso</titulo>
    <director>Leo McCarey</director>
  </pelicula>
</peliculas>
